basic_settings:
  site_title: PROTEUS Framework
  favicon_light: /assets/img/brand/PROTEUS_black_on_white_logo_only.png
  favicon_dark: /assets/img/brand/PROTEUS_white_on_black_logo_only.png

header_settings:
  logo_image: /assets/img/brand/PROTEUS_white_on_black.png
  mobile_logo_image: /assets/img/brand/PROTEUS_white_on_black.png
  # Choose a color for your header [blue, dark, light].
  theme: dark
  # If the page has a featured image, it turns transparent if allow_transparent is set to "yes".
  allow_transparent: "yes"

home_settings:
  # Choose a layout for your home page:
    # landing - an example landing page made using the Argon design system
    # papers - use your papers as the home page
  theme: landing

blog_settings:
  theme: basic
  read_more: "no"

menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'

    - title: 'Documentation'
      submenu_items:
      - title: PROTEUS
        url: https://proteus-framework.org/PROTEUS/
        icon: ni-books text-primary
      - title: Modules
        url: /modules
        icon: ni-bold-right text-primary

    - title: 'Demos'
      url: '/demos'

    - title: 'Publications'
      url: '/publications'

    - title: 'People & Contact'
      url: '/people'

footer_settings:
  footer_tagline: PROTEUS framework for planetary evolution

social_settings:
  github_url: 'https://github.com/FormingWorlds/PROTEUS'

authors:
  nicholls:
    name: Harrison Nicholls
  lichtenberg:
    name: Tim Lichtenberg

advanced_settings:
  analytics_code: '<script async src="https://www.googletagmanager.com/gtag/js?id=G-ZCDRX6PC62"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag("js",new Date());gtag("config","G-ZCDRX6PC62");</script>'
  header_js:
  footer_js:
